---
 - name: welcome to Playbook2 - patching one
   debug:
     msg: " welcome to Playbook2 - call Playbook3 (del wsus)"

- name: call the roll Playbook3 - Delete WSUS Settings
  include_role:
    name: playbook3

- name: Done Playbook3
  debug:
    msg: "Done Playbook3 - continue with Playbook2"
